#! /bin/bash

MY_HOSTNAME=""

# check whether the user input domain name or not 
if [ -z "$1" ]; then
    echo -e "\n"
    read -p "Enter the hostname (without .local): " MY_HOSTNAME
else
    echo -e "\n"
    MY_HOSTNAME=$1
    echo "Enter the hostname: " ${MY_HOSTNAME}
fi


# auto add .local to the hostname
MY_HOSTNAME=${MY_HOSTNAME}\.local


# make www folder if it doesn't exist
if [ ! -d /var/www/${MY_HOSTNAME} ]; then
    sudo mkdir /var/www/${MY_HOSTNAME}
    echo "created /var/www/${MY_HOSTNAME}"
fi


# change ownership of the folder into current user, so they can change the code
# without the need of sudo 
sudo chmod -R 755 /var/www/${MY_HOSTNAME}
sudo chown -R $USER:$USER /var/www/${MY_HOSTNAME}
echo "done: change owner of /var/www/${MY_HOSTNAME}"


# make nginx server-block configuration file if it doesn't exist
if [[ ! -f /etc/nginx/sites-available/${MY_HOSTNAME}.conf ]]; then
    sudo touch /etc/nginx/sites-available/${MY_HOSTNAME}.conf
    echo "done: create /etc/nginx/sites-available/${MY_HOSTNAME}.conf"
else 
    echo "FAILED: create /etc/nginx/sites-available/${MY_HOSTNAME}.conf"
    echo "------- server-block configuration already exist"
fi


# write server-block configuration
echo "server {
    listen      80;
    listen      [::]:80;
    server_name ${MY_HOSTNAME} www.${MY_HOSTNAME};
    root        /var/www/${MY_HOSTNAME};
    location    / {
        try_files \$uri \$uri/ =404;
    }

    location ~ \.php\$ {
        fastcgi_pass    unix:/run/php-fpm/www.sock;
        fastcgi_param   SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        fastcgi_index   index.php;
        include         fastcgi_params;
    }
}" | sudo tee -a /etc/nginx/sites-available/${MY_HOSTNAME}.conf > /dev/null
echo "done: setup /etc/nginx/sites-available/${MY_HOSTNAME}.conf"


# linked the server-block configuration
if [[ ! -f /etc/nginx/sites-enabled/${MY_HOSTNAME}.conf ]]; then
    sudo ln -s /etc/nginx/sites-available/${MY_HOSTNAME}.conf /etc/nginx/sites-enabled/
    echo "done: link sites-enabled for /etc/nginx/sites-available/${MY_HOSTNAME}.conf"
else
    echo "FAILED: link sites-enabled for /etc/nginx/sites-available/${MY_HOSTNAME}.conf"
    echo "------- server-block configuration has been linked"
fi


# check if dns already declared in the hosts file or not
if grep -Fxq "127.0.0.1   ${MY_HOSTNAME} # generated by alvin-make-www" /etc/hosts
then
    # code if found
    echo "FAILED: added dns ${MY_HOSTNAME} to the hosts file"
    echo "------- dns already exist in hosts file"
else
    # if not found, add dns to the host file
    echo "127.0.0.1   ${MY_HOSTNAME} # generated by alvin-make-www" | sudo tee -a /etc/hosts > /dev/null
    echo "done: add dns ${MY_HOSTNAME} to the hosts file"
fi

# restart Nginx
sudo systemctl restart nginx
echo "done: nginx restarted"


echo "hostname: ${MY_HOSTNAME}"
echo "completed: alvin-make-www.sh"